apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: helm-controller.fluxcd.community.tanzu.vmware.com.0.21.0+update.1
spec:
  refName: helm-controller.fluxcd.community.tanzu.vmware.com
  version: 0.21.0+update.1
  releaseNotes: "Adding placeholder secrets for authenticated registeries"
  releasedAt: "2022-12-15T15:14:08Z"
  capacityRequirementsDescription: ""
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/fluxcd-helm-controller-bundle:0.21.0_update.1
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      properties:
        namespace:
          type: string
          description: Deployment and service namespace
          default: helm-system
        limits_cpu:
          type: string
          description: Set cpu usuage limit
          default: 1000m
        limits_memory:
          type: string
          description: Set memory usuage limit
          default: 1Gi
